### ISSUE TITLE
vscodeの設定UIでuroborosql-fmtの設定出来るようにする

### ISSUE THREAD

**Issue by tanzaku** [future-architect/vscode-uroborosql-fmt#19]
現状では、フォーマットの各設定は `uroborosql-fmt.configurationFilePath` で指定したファイルに記載する方式になっているが、vscodeの設定UIで設定できるようにする。

### 現時点での実現方法のイメージ
 [settings.json の変更イベント](https://code.visualstudio.com/api/references/vscode-api#:~:text=affectsConfiguration) 発生時に、設定の変更内容を uroborosql-fmt.configurationFilePath で指定している設定ファイルに反映し、実際のフォーマット時には uroborosql-fmt.configurationFilePath の設定を読み込んで動作する。

**Comment by ota-meshi** [comment]
settings.jsonの構成の値は常に無視するということですか？
ユーザーごとにユーザー設定を変えそれをconfigurationFileに保存しpushした場合、ユーザーによっては意図しない動きだと認識されると思います。そのためあまり良い方法とは思いません 🤔 

代わりに、settings.jsonの構成の値はconfigurationFileからのoverrideで受け入れられるようにしたうえで、settings.jsonの値をconfigurationFileに同期するコマンドを追加するのはどうですか？

**Comment by tanzaku** [comment]
> ユーザーごとにユーザー設定を変えそれをconfigurationFileに保存しpushした場合、ユーザーによっては意図しない動きだと認識されると思います。そのためあまり良い方法とは思いません 🤔

確かにそうですね…

> 代わりに、settings.jsonの構成の値はconfigurationFileからのoverrideで受け入れられるようにしたうえで、settings.jsonの値をconfigurationFileに同期するコマンドを追加するのはどうですか？

ありがとうございます、こちらの案良さそうですね！
